# Generated by Django 5.0.6 on 2024-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elddata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=20)),
                ('violation_time', models.DateTimeField()),
                ('violation_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='elddata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
