# Generated by Django 5.0.6 on 2024-07-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elddata', '0002_hosviolation_alter_elddata_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosviolation',
            old_name='driver_id',
            new_name='driverId',
        ),
    ]
